name: verify-bundle

on:
  push:
    branches:
      - master

jobs:
  verify-all:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: pip3 install -U online-judge-verify-helper
    - name: Run tests
      run: | 
        ulimit -s unlimited
        python3 verify.py bundle